# Generated by Django 3.1.1 on 2020-09-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='census_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('pop_total', models.PositiveIntegerField()),
                ('pop_males', models.PositiveIntegerField()),
                ('pop_females', models.PositiveIntegerField()),
                ('lit_total', models.PositiveIntegerField()),
                ('lit_males', models.PositiveIntegerField()),
                ('lit_females', models.PositiveIntegerField()),
                ('sex_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('literacy_rate_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('literacy_rate_males', models.DecimalField(decimal_places=2, max_digits=5)),
                ('literacy_rate_females', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
