# Generated by Django 3.1.1 on 2020-09-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_census_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census_data',
            name='literacy_rate_females',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='census_data',
            name='literacy_rate_males',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='census_data',
            name='literacy_rate_total',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='census_data',
            name='sex_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
